/* OS Interview Mode 題庫：每題有提示、30 秒版、60 秒完整版、可能的追問 */
window.INTERVIEW_QUESTIONS = [
  { id: 'iv-proc-thread', tag: 'Process & Thread', q: 'Process 和 Thread 有什麼差別？',
    hint: '從「共享什麼、各自擁有什麼」講起，再推出「為什麼比較輕」與「代價」。',
    a30: '<p>Process 是資源分配的單位，有自己獨立的位址空間；Thread 是 CPU 排程的單位，同一個 process 裡的 threads 共享 code、data、heap 和開啟的檔案，但各自有 stack、PC 和暫存器。因為不用建立或切換位址空間，thread 的建立與切換都比 process 便宜；代價是沒有隔離，一個 thread 崩潰整個 process 一起死，共享資料也要用同步機制保護。</p>',
    a60: '<p>Process 是「執行中的程式」，OS 為它配置獨立的位址空間、開啟檔案表、PCB。Thread 是 process 內的一條執行流，只擁有執行所需的最小狀態：program counter、暫存器、自己的 stack。同一 process 的所有 thread 共享 text、data、heap 和開啟的檔案。</p><p>因此 thread 比較輕：建立時不用複製位址空間、只要配一個 stack；context switch 時不用換 page table，TLB 和 cache 不會失效；溝通直接讀寫共享記憶體，不用 IPC。</p><p>代價：沒有保護。一個 thread 的 segfault 會殺掉整個 process；共享的資料需要 mutex、semaphore 等同步機制，否則會有 race condition。所以 Chrome 用 process 隔離分頁（穩定性優先），而伺服器的 worker 常用 thread（效率優先）。</p>',
    followup: '「fork 之後全域變數會共享嗎？」——不會，各自一份（copy-on-write）。「user-level 與 kernel-level thread 的差別？」——kernel 是否知道它存在；user-level 一個阻塞全部阻塞，也無法用多核。',
    link: '#/ch/ch2/process-vs-thread' },
  { id: 'iv-heap-stack', tag: 'Process & Thread', q: 'Heap 和 Stack 有什麼差別？',
    hint: '誰管理、多快、多大、生命週期、thread 各自還是共享。舉 int x 與 new int 的例子。',
    a30: '<p>Stack 存區域變數、參數、返回位址，由編譯器自動管理——函式呼叫推 frame、返回就彈掉，配置只是移動 stack pointer，極快但大小有限。Heap 存 new/malloc 動態配置的物件，由程式員手動釋放，可以很大但配置較慢、會碎片化、忘記釋放就 memory leak。<code>int x = 5</code> 在 stack，<code>int* p = new int(10)</code> 的 p 在 stack、那個 10 在 heap。</p>',
    a60: '<p>兩者都是 process 位址空間的一部分，從兩端往中間長。Stack 在高位址往下長，每呼叫一個函式推一個 frame（參數、區域變數、返回位址），返回就自動彈掉，所以生命週期綁定函式作用域、配置只是 SP 加減，非常快；但大小有限（通常 8 MB），遞迴太深會 stack overflow，回傳區域變數的位址是 dangling pointer。</p><p>Heap 往上長，放 new/malloc 的物件，大小執行期才決定，可以很大；但要手動 free/delete，否則 memory leak；配置器要找合適的空閒區塊，較慢且有碎片。</p><p>多執行緒下：每個 thread 有自己的 stack，heap 是共享的——這也是為什麼 heap 上的資料需要同步。</p>',
    followup: '「static 變數在哪？」——data 段。「stack overflow 和 heap 用完各是什麼錯誤？」——前者通常 segfault，後者 malloc 回傳 NULL / bad_alloc。',
    link: '#/ch/ch1/memory-layout' },
  { id: 'iv-context-switch', tag: 'Process & Thread', q: '什麼是 Context Switch？',
    hint: '保存到哪、載入從哪、為什麼是 overhead、隱性成本。',
    a30: '<p>Context switch 是 CPU 從一個 process 換到另一個的過程：kernel 把目前 process 的 PC、暫存器、狀態存進它的 PCB，再從下一個 process 的 PCB 把這些值載回 CPU，並切換 page table。這段時間 CPU 沒做任何有用的工作，是純 overhead；而且切換後 cache 和 TLB 都失效，所以切換太頻繁會拖慢系統。</p>',
    a60: '<p>單核 CPU 一次只能執行一個 process，「多工」是靠快速切換造成的錯覺。切換的觸發點通常是 timer interrupt、I/O interrupt，或 process 自己呼叫阻塞的 system call。</p><p>流程：CPU 進入 kernel mode → 把目前 process 的 context（PC、所有暫存器、狀態）保存到它的 PCB → scheduler 選下一個 → 從新 PCB 載入 context、切換 page table 暫存器 → 切回 user mode 從新 PC 繼續。新舊 process 都感覺不到自己被暫停過。</p><p>成本有直接的（kernel 執行幾微秒）和間接的（cache、TLB、branch predictor 內容失效）。這是 Round Robin 的 quantum 不能太小的原因，也是 thread 切換比 process 切換便宜的原因——thread 不用換位址空間。</p>',
    followup: '「context switch 和 mode switch 一樣嗎？」——不一樣。system call 只是 mode switch（同一 process、user↔kernel），不一定換 process。',
    link: '#/ch/ch1/context-switch' },
  { id: 'iv-pc', tag: 'Process & Thread', q: 'Program Counter 是什麼？',
    hint: '一個暫存器、存什麼、CPU 迴圈、為什麼要存進 PCB。',
    a30: '<p>Program Counter 是 CPU 裡的一個暫存器，存「下一條要執行的指令的記憶體位址」。CPU 的基本迴圈就是讀 PC 指向的指令、執行、把 PC 指向下一條。所以一個 process「執行到哪裡」完全由 PC 決定；context switch 時把 PC 存進 PCB，之後載回來就能從原地繼續。</p>',
    a60: '<p>PC（有些架構叫 instruction pointer）是控制 CPU 執行流的暫存器。每個 cycle CPU 取出 PC 指向的指令，執行，然後 PC 加上指令長度；跳躍、呼叫、返回指令則直接改寫 PC。</p><p>它是 process 狀態中最關鍵的一項：保存了 PC 就保存了「進度」。PCB 裡存的 PC 只有在 process 沒在跑的時候才是最新的；process 正在執行時，真正的 PC 在 CPU 暫存器裡。同一 process 的每個 thread 各有一個 PC，因為每條執行流的進度不同。</p><p>Interrupt 發生時硬體會自動把 PC 推進 kernel stack，handler 結束後還原——這就是為什麼被中斷的程式能無縫接回。</p>',
    followup: '「PC 和 stack pointer 的差別？」——PC 指向指令，SP 指向 stack 頂端；兩者都是 context 的一部分。',
    link: '#/ch/ch1/pcb' },
  { id: 'iv-process-states', tag: 'Process & Thread', q: 'Process 有哪些狀態？I/O 完成後 process 會直接變 Running 嗎？',
    hint: '五個狀態、五個轉換、Ready 與 Waiting 的差別。',
    a30: '<p>New、Ready、Running、Waiting、Terminated。Ready 是「只差 CPU」，Waiting 是「在等某個事件，給了 CPU 也沒用」。I/O 完成後 process 從 Waiting 變 Ready，進 ready queue 排隊，要等 scheduler 選到它才 Running——不會直接搶回 CPU（除非是搶佔式排程且它優先權更高）。</p>',
    a60: '<p>New：正在建立。Ready：在 ready queue 等 CPU。Running：正在某顆 CPU 上執行，每顆 CPU 同時只有一個。Waiting（Blocked）：在等 I/O 或事件。Terminated：結束等回收。</p><p>轉換：admit（New→Ready）、dispatch（Ready→Running）、timer interrupt 或被搶佔（Running→Ready）、I/O request（Running→Waiting）、I/O complete（Waiting→Ready）、exit（Running→Terminated）。</p><p>關鍵是 Ready 與 Waiting 的區別：scheduler 只從 Ready 挑人，因為 Waiting 的 process 給了 CPU 也無事可做。I/O 完成是由 interrupt handler 把 process 改成 Ready；它是否立刻執行取決於排程策略。</p>',
    followup: '「Running→Ready 和 Running→Waiting 的差別？」——前者是被動被踢（還能跑），後者是主動等（不能跑）。',
    link: '#/ch/ch1/process-state' },
  { id: 'iv-race', tag: 'Synchronization', q: 'Race Condition 是什麼？舉一個例子。',
    hint: '用 counter++ 拆成三條指令的例子；講「結果取決於時序」。',
    a30: '<p>Race condition 是多個 thread 同時存取並修改共享資料，最後結果取決於它們交錯執行的順序。例如 counter++ 其實是 LOAD、ADD、STORE 三條指令；兩個 thread 各做一次，如果 A 剛 LOAD 到 0 就被切走、B 完整跑完寫回 1、A 再用過期的 0 加一寫回 1，最後就是 1 而不是 2。解法是用 lock 讓這段程式碼成為 critical section。</p>',
    a60: '<p>共享資料上的 read-modify-write 操作若不是原子的，就可能在中途被 context switch 打斷，而另一個 thread 在這期間也讀寫了同一份資料。以 counter++ 為例：LOAD reg, counter；ADD reg, 1；STORE counter, reg。兩個 thread 從 0 開始各做一次，交錯順序 A-LOAD、B-LOAD、A-ADD、A-STORE、B-ADD、B-STORE 會得到 1——B 的寫入覆蓋了 A 的。</p><p>它難以除錯是因為結果取決於時序：大部分時候正確，偶爾出錯，加 print 可能改變時序讓 bug 消失。</p><p>解法：把存取共享資料的區段變成 critical section，用 mutex 保證一次只有一個 thread 在裡面；或用硬體原子指令（atomic fetch_add）直接完成。</p>',
    followup: '「單核也會有 race 嗎？」——會，timer interrupt 隨時可能切換。「用 volatile 能解決嗎？」——不能，volatile 只防編譯器最佳化，不提供原子性。',
    link: '#/ch/ch4/race-condition' },
  { id: 'iv-cs-conditions', tag: 'Synchronization', q: 'Critical Section 問題的三個條件是什麼？',
    hint: '每個條件配一個「違反它的爛解法」當例子。',
    a30: '<p>Mutual Exclusion：一次只能一個 process 在 critical section。Progress：沒人在裡面且有人想進時，不能被「不想進的人」卡住，決定必須在有限時間內做出。Bounded Waiting：一個 process 提出請求後，其他人進入的次數有上限，不會無限期被插隊。</p>',
    a60: '<p>Critical section 是存取共享資料的程式碼區段，解法要設計 entry 和 exit section 並滿足三個條件。</p><p>Mutual exclusion：任何時刻至多一個 process 在 critical section——這是基本要求。Progress：若無人在 critical section 且有人想進入，則只有想進入的 process 能參與決定，且決定不能無限延遲——「嚴格輪流」的解法違反這條，因為不想進的一方會擋住想進的一方。Bounded waiting：從請求到獲准之間，其他 process 進入的次數有上限——簡單的 test_and_set spinlock 違反這條，因為誰搶到鎖是隨機的。</p><p>Peterson\'s solution 是同時滿足三者的經典軟體解法；mutex、semaphore 則是 OS 提供的工具。</p>',
    followup: '「Progress 和 Bounded Waiting 差在哪？」——Progress 是「不會大家都卡在門外」，Bounded Waiting 是「不會有人永遠進不去」。',
    link: '#/ch/ch4/critical-section' },
  { id: 'iv-mutex-sem', tag: 'Synchronization', q: 'Mutex 和 Semaphore 有什麼不同？',
    hint: '擁有權、計數、用途（互斥 vs 同步）。',
    a30: '<p>Mutex 是一把鎖，只有 0/1 兩種狀態，而且有擁有權——誰 lock 誰 unlock，用來做互斥。Semaphore 是一個計數器加上 wait/signal 兩個原子操作，沒有擁有權，任何人都可以 signal；初始值 N 可以管理 N 個相同資源，初始值 0 可以當作事件用來控制執行順序。Binary semaphore 功能上像 mutex，但語意不同。</p>',
    a60: '<p>Mutex 的語意是「互斥」：保護一段 critical section，一次只能一個 thread 持有；它有擁有權概念，只有持有者能釋放，很多實作會檢查這點，也支援遞迴鎖、優先權繼承。</p><p>Semaphore 的語意是「計數／同步」：wait 把值減一、小於零就阻塞；signal 加一、有人在等就叫醒。初始值 N 的 counting semaphore 表示 N 個可用資源；初始值 0 可以讓 thread B 等 thread A 完成某件事——A 執行 signal、B 執行 wait，這在 mutex 是不允許的（不能 unlock 別人的鎖）。</p><p>Producer-consumer 是最好的例子：mutex 保護 buffer，empty 和 full 兩個 counting semaphore 控制「滿了要等」與「空了要等」。</p>',
    followup: '「binary semaphore 可以取代 mutex 嗎？」——功能上可以，但失去擁有權檢查與優先權繼承。「semaphore 的 wait 會 busy waiting 嗎？」——經典實作是 block 進等待佇列，不 spin。',
    link: '#/ch/ch5/semaphore' },
  { id: 'iv-deadlock', tag: 'Deadlock', q: 'Deadlock 的四個必要條件是什麼？如何避免？',
    hint: '四個條件各一句話，再講「打破哪一個最實用」。',
    a30: '<p>Mutual Exclusion（資源一次只能一人用）、Hold and Wait（拿著資源還在等別的）、No Preemption（資源不能被強制收回）、Circular Wait（形成環狀等待）。四個同時成立才會 deadlock。最實用的預防是打破 circular wait：規定所有 lock 必須依固定順序取得。</p>',
    a60: '<p>Deadlock 是一組 process 互相等待對方持有的資源，永遠無法前進。四個必要條件：mutual exclusion——至少一個資源不可共享；hold and wait——process 持有資源同時等待其他資源；no preemption——資源只能由持有者自願釋放；circular wait——存在 P0 等 P1、P1 等 P2、…、Pn 等 P0 的環。</p><p>處理策略有四種：prevention 在設計上打破某個條件，例如 lock ordering 打破 circular wait、一次申請全部資源打破 hold and wait；avoidance 用 Banker\'s algorithm 確保每次分配後仍是 safe state；detection 定期找 RAG 的環再 recovery（殺 process 或搶資源）；或者像多數 OS 一樣忽略，交給應用程式自己處理。</p>',
    followup: '「Deadlock 和 Starvation 的差別？」——deadlock 永遠無法前進；starvation 理論上可能前進只是一直沒輪到。「RAG 有環一定 deadlock 嗎？」——單實例資源是；多實例只是必要條件。',
    link: '#/ch/ch6/deadlock-intro' },
  { id: 'iv-banker', tag: 'Deadlock', q: "Banker's Algorithm 是怎麼運作的？",
    hint: 'Need = Max − Allocation；安全序列；請求時先假裝分配再檢查。',
    a30: '<p>每個 process 事先宣告最大需求 Max，系統記錄已分配 Allocation、剩餘 Available，算出 Need = Max − Allocation。安全性檢查：從 Available 出發，找一個 Need 能被滿足的 process，假設它完成並歸還 Allocation，重複直到所有 process 都能完成（safe）或找不到（unsafe）。有請求時先假裝分配，安全才真的給，否則讓它等。</p>',
    a60: '<p>它是 deadlock avoidance 的演算法，適用於多實例資源。系統維護 Available（每種資源剩幾個）、Max（每個 process 最多要幾個）、Allocation（已拿幾個）、Need = Max − Allocation。</p><p>安全性演算法：Work = Available，Finish 全 false；找一個未完成且 Need ≤ Work 的 process，把它的 Allocation 加回 Work、標記完成；重複直到全部完成（safe，找到的順序是 safe sequence）或無法再找到（unsafe）。</p><p>資源請求演算法：請求必須 ≤ Need（否則錯誤）且 ≤ Available（否則等待）；然後假裝分配並跑安全性檢查，safe 才真的分配，unsafe 就還原讓它等。</p><p>缺點是要事先知道最大需求且 process 數固定，實務上少用，但它是理解 safe state 的最佳教材。</p>',
    followup: '「Unsafe 一定 deadlock 嗎？」——不一定，只是無法保證不會。',
    link: '#/ch/ch6/banker' },
  { id: 'iv-preempt', tag: 'CPU Scheduling', q: 'Preemptive 和 Non-preemptive Scheduling 差在哪？',
    hint: '「誰決定 CPU 什麼時候換人」；舉 SJF vs SRTF。',
    a30: '<p>Non-preemptive：process 拿到 CPU 後會一直跑到結束或自己去等 I/O，OS 不會中途拿走；例如 FCFS、SJF。Preemptive：OS 可以在 timer 到期、更高優先權或更短工作到達時強制收回 CPU；例如 RR、SRTF。搶佔的 response time 好、不會被無窮迴圈卡死，但 context switch 多，且共享資料需要同步。</p>',
    a60: '<p>排程決策發生在四個時機：process 進入 Waiting、Running 變 Ready（timer 或被搶佔）、Waiting 變 Ready、process 結束。只在第一和第四時機做決策就是 non-preemptive——換人完全由 process 自願；四個時機都做就是 preemptive。</p><p>用 SJF 和 SRTF 對比：P1 在 t=0 到達 burst 8，P2 在 t=1 到達 burst 4。SJF 讓 P1 跑完再跑 P2；SRTF 在 t=1 發現 P2 的 4 小於 P1 剩餘的 7，立刻搶佔。SRTF 的平均等待時間更低，但 P1 被中斷。</p><p>Preemptive 的代價：更多 context switch，以及 kernel 資料結構可能在更新中途被打斷——所以 preemptive kernel 需要 lock。互動式系統幾乎都是 preemptive。</p>',
    followup: '「Windows / Linux 是哪種？」——都是 preemptive。「preemptive 和 preemptive kernel 是同一件事嗎？」——前者是排程 user process，後者是 kernel 本身的程式碼可被搶佔。',
    link: '#/ch/ch3/preemption' },
  { id: 'iv-sched-metrics', tag: 'CPU Scheduling', q: 'Turnaround Time、Waiting Time、Response Time 各是什麼？怎麼算？',
    hint: '三個公式，然後說明搶佔時 waiting 與 response 為什麼不同。',
    a30: '<p>Turnaround = 完成時間 − 到達時間，是從進來到出去的總時間。Waiting = Turnaround − Burst，是在 ready queue 純等待的時間。Response = 第一次拿到 CPU 的時間 − 到達時間。非搶佔時 waiting 等於 response；搶佔時 process 第一次執行後可能再被中斷，waiting 會大於 response。</p>',
    a60: '<p>這三個量都從 Gantt chart 讀出來。以 FCFS 排 P1(0, 8)、P2(1, 4)、P3(2, 2) 為例：Gantt 是 P1 0–8、P2 8–12、P3 12–14。P2 的 turnaround = 12 − 1 = 11，waiting = 11 − 4 = 7，response = 8 − 1 = 7。</p><p>排程演算法不能改變 burst，只能改變等待，所以比較演算法主要看平均 waiting time；互動系統則看 response time。SJF 對平均 waiting 最佳，RR 對 response 最好但 turnaround 較差。</p>',
    followup: '「哪個演算法平均等待時間最小？」——SJF/SRTF（可證明），但需要預估 burst。',
    link: '#/ch/ch3/metrics' },
  { id: 'iv-rr-quantum', tag: 'CPU Scheduling', q: 'Round Robin 的 time quantum 太大或太小會怎樣？',
    hint: '兩個極端各退化成什麼；context switch overhead。',
    a30: '<p>Quantum 太大，沒有人會被 timer 打斷，RR 退化成 FCFS，response time 變差。Quantum 太小，每跑一下就 context switch，overhead 占比太高，CPU 大部分時間在切換而不是做事。經驗法則是讓大多數 CPU burst 都在一個 quantum 內完成，且 quantum 遠大於 context switch 時間，常見 10–100 ms。</p>',
    a60: '<p>RR 是 FCFS 加上時間片：每個 process 一次最多跑 q，時間到就回 ready queue 尾端。它保證 n 個 process 中每個最多等 (n−1)q 就能再拿到 CPU，所以 response 好、沒有 starvation。</p><p>q 趨近無限大就是 FCFS；q 趨近 context switch 時間（幾微秒）則有一半以上的時間在切換。此外 q 也影響 turnaround：如果 q 剛好能讓大部分 process 一次跑完，turnaround 最好；教科書建議 80% 的 burst 應短於 q。</p><p>Linux 的 CFS 不用固定 quantum，而是依權重分配時間比例，但思想相同。</p>',
    followup: '「RR 的平均 turnaround 為什麼通常比 SJF 差？」——長短工作被平均對待，短工作也要等好幾輪。',
    link: '#/ch/ch3/rr' },
  { id: 'iv-vm', tag: 'Memory', q: '什麼是 Virtual Memory？為什麼需要它？',
    hint: '邏輯與實體分離、demand paging、三個好處。',
    a30: '<p>Virtual memory 把程式看到的邏輯位址空間和實體 RAM 分開：每個 process 以為自己有一整片連續、從 0 開始的記憶體，實際上 page 散在 RAM 各處，甚至有些在磁碟上、需要時才載入（demand paging）。好處是程式可以大於實體記憶體、多個程式互相隔離、記憶體利用率高——只有正在用的 page 才佔 RAM。</p>',
    a60: '<p>它建立在 paging 之上，再加上「page 不一定要在 RAM」這個想法。Page table 每項有 valid bit，存取 valid = 0 的頁會產生 page fault，OS 從磁碟載入後重新執行指令。程式對此完全無感。</p><p>三個效果：一、程式的位址空間可以遠大於 RAM（64 位元位址空間 vs 16 GB）。二、每個 process 有獨立的 page table，天然隔離與保護，同時也能共享頁（共享函式庫、copy-on-write 的 fork）。三、只載入用到的部分，所以能同時跑更多程式，啟動也快。</p><p>代價是 page fault 極慢（毫秒級 vs 奈秒級），且如果 process 的 working set 放不進 RAM 會 thrashing。</p>',
    followup: '「malloc 1 GB 為什麼馬上成功？」——只配虛擬位址，實體頁在第一次寫入時才分配。',
    link: '#/ch/ch8/virtual-memory' },
  { id: 'iv-page-fault', tag: 'Memory', q: 'Page Fault 發生時 OS 做什麼？',
    hint: '照順序講：trap → 檢查 → 找 frame → 磁碟 → 更新表 → 重新執行。',
    a30: '<p>MMU 查 page table 發現 valid bit 為 0，產生 trap 進 kernel。OS 先確認這是合法位址（否則 segfault），然後找一個空 frame（沒有就用 page replacement 選 victim，dirty 的要先寫回），對磁碟下 I/O 把 page 讀進 frame——這期間 process 進 Waiting，CPU 給別人——完成後更新 page table、valid 設 1，process 回 Ready，之後重新執行那條指令。</p>',
    a60: '<p>Page fault 是硬體無法完成位址翻譯時交給 OS 處理的機制。步驟：一、MMU 發現 valid = 0，trap。二、OS 查 process 的記憶體描述，判斷是合法的未載入頁還是非法存取；非法就送 SIGSEGV。三、找 free frame；沒有就跑 replacement 演算法（FIFO、LRU、clock）選 victim，若 victim 的 dirty bit 為 1 要先寫回磁碟。四、排程磁碟讀取，process 設為 Waiting，context switch 給別的 process。五、磁碟 interrupt 通知完成，OS 更新 page table（frame 號碼、valid = 1），process 設為 Ready。六、process 再度被排程時，重新執行引發 fault 的那條指令，這次翻譯成功。</p><p>一次 major fault 約幾毫秒，是記憶體存取的數萬倍，所以 page fault rate 必須極低。</p>',
    followup: '「page fault 和 segfault 的關係？」——segfault 是 page fault 處理中判定為非法存取的結果。「minor fault 是什麼？」——頁其實在 RAM，只需更新表，不用讀磁碟。',
    link: '#/ch/ch8/page-fault' },
  { id: 'iv-paging', tag: 'Memory', q: 'Paging 解決了什麼問題？帶來什麼新問題？',
    hint: '解決 external fragmentation；帶來 internal fragmentation、page table 空間、多一次存取。',
    a30: '<p>Paging 把 process 切成固定大小的 page、RAM 切成同大的 frame，任何 page 可以放任何 frame，所以 process 不需要連續存放——解決了連續配置的 external fragmentation。新問題：最後一頁用不滿造成 internal fragmentation；每個 process 要一張 page table，占空間；每次記憶體存取要先查表，多一次記憶體存取，所以需要 TLB。</p>',
    a60: '<p>連續配置下，process 必須佔一整塊連續空間，久了會有很多小 hole，總量夠但沒有一塊夠大（external fragmentation），只能靠昂貴的 compaction。Paging 讓邏輯位址被拆成 page number 和 offset：page number 查 page table 得到 frame number，offset 不變，實體位址 = frame × page size + offset。因為 frame 都一樣大，任何空 frame 都能用。</p><p>代價：一、internal fragmentation，平均每個 process 浪費半頁。二、page table 可能很大（32 位元、4 KB page 就有 100 萬項），需要多層 page table 或 inverted page table。三、每次存取多一次查表，用 TLB 快取最近的翻譯來解決，hit ratio 通常 99% 以上。</p><p>Paging 也是 virtual memory、共享記憶體、記憶體保護的基礎。</p>',
    followup: '「page size 大小的取捨？」——大：table 小、I/O 效率高、碎片多；小：反之。',
    link: '#/ch/ch7/paging' },
  { id: 'iv-tlb', tag: 'Memory', q: 'TLB 是什麼？為什麼需要它？',
    hint: '「page table 在記憶體」→ 每次存取兩次 → cache。EAT 公式。',
    a30: '<p>Page table 放在記憶體，所以 paging 下每次存取資料都要先讀一次記憶體查表，存取時間加倍。TLB 是 MMU 裡的小型快取，存最近用過的 page → frame 翻譯；hit 就直接得到 frame 不用查表。因為程式有局部性，幾十到幾百個項目的 TLB 就能達到 99% 以上的命中率。</p>',
    a60: '<p>TLB 是 associative memory，所有項目平行比對，一個 cycle 內回答。流程：CPU 產生邏輯位址 → 用 page number 查 TLB → hit 則取得 frame，總共一次記憶體存取；miss 則查 page table（多一次存取），再把結果放進 TLB。</p><p>Effective access time = hit ratio × (TLB 時間 + 記憶體時間) + miss ratio × (TLB 時間 + 2 × 記憶體時間)。例如 TLB 10 ns、記憶體 100 ns、hit 98%：EAT = 0.98 × 110 + 0.02 × 210 = 112 ns。</p><p>Context switch 時 TLB 內容屬於舊 process，必須清空（flush），或用 ASID 標記每個項目屬於哪個位址空間。這是 process 切換比 thread 切換昂貴的原因之一。</p>',
    followup: '「TLB miss 和 page fault 差在哪？」——TLB miss 頁在 RAM，硬體查表幾十 ns；page fault 頁不在 RAM，OS 做磁碟 I/O 幾 ms。',
    link: '#/ch/ch7/tlb' },
  { id: 'iv-lru', tag: 'Memory', q: 'FIFO、LRU、Optimal page replacement 各怎麼運作？哪個最好？',
    hint: '各一句話；OPT 是下界；LRU 近似 OPT；Belady\'s anomaly。',
    a30: '<p>FIFO 踢最早載入的頁，簡單但常踢掉常用頁，還有 Belady\'s anomaly——frame 變多 fault 反而變多。Optimal 踢未來最久才會用到的頁，fault 最少，但需要知道未來，只當基準。LRU 踢過去最久沒用的頁，用局部性近似 OPT，效果好但完整實作成本高，實務用 clock 等近似演算法。</p>',
    a60: '<p>教科書 reference string 7 0 1 2 0 3 0 4 2 3 0 3 2 1 2 0 1 7 0 1、3 個 frame：FIFO 15 次 fault、LRU 12 次、OPT 9 次。</p><p>FIFO 用一個 queue，實作最簡單，但「載入時間」與「是否還會用」無關。OPT 證明了下界，用來評估其他演算法。LRU 基於「最近用過的很可能再用」，需要每次存取都記錄時間或更新串列，硬體很少完整支援，所以用 reference bit 做近似：second-chance/clock 演算法沿 FIFO 順序掃，reference bit 為 1 的清零並跳過、為 0 的當 victim。</p><p>LRU 和 OPT 是 stack algorithm（n 個 frame 的內容永遠是 n+1 個 frame 的子集），所以沒有 Belady\'s anomaly；FIFO 不是。</p>',
    followup: '「dirty bit 有什麼用？」——victim 若沒被改過可直接丟棄，省一次磁碟寫入。',
    link: '#/ch/ch8/page-replacement' },
  { id: 'iv-thrashing', tag: 'Memory', q: 'Thrashing 是什麼？怎麼解決？',
    hint: '定義、惡性循環、working set。',
    a30: '<p>Thrashing 是 process 花在 page fault 處理（RAM 與磁碟間搬頁）的時間比執行還多，CPU 使用率崩跌。原因是每個 process 分到的 frame 少於它的 working set。解法：用 working-set model 或 page-fault frequency 控制同時執行的 process 數，必要時把某個 process 整個 swap out，或增加 RAM。</p>',
    a60: '<p>當 multiprogramming 程度太高，每個 process 的常用頁（working set）放不進它分到的 frame，一執行就 fault、踢掉別人的頁、別人執行又 fault。CPU 看起來很閒，傳統 OS 會誤判為「可以再載入更多 process」，讓情況更糟——這是惡性循環。</p><p>Working-set model：用最近 Δ 次存取觸及的頁集合估計每個 process 的需求 WSS，若 ΣWSS 超過總 frame 數就 suspend 某個 process。Page-fault frequency：直接量測 fault 率，太高就給更多 frame、太低就收回，沒有 frame 可給就 swap out。用 local replacement 也能避免一個 process 的 thrashing 傳染給其他人。</p>',
    followup: '「怎麼在系統上觀察到 thrashing？」——CPU 使用率低、swap I/O 極高、每個程式都慢。',
    link: '#/ch/ch8/thrashing' },
  { id: 'iv-syscall', tag: 'OS 基礎', q: 'System Call 是什麼？和一般函式呼叫有什麼不同？',
    hint: 'user/kernel mode、trap 指令、為什麼不能直接碰硬體。',
    a30: '<p>System call 是 user 程式向 kernel 請求服務的介面，例如 read、write、fork。它和一般函式呼叫的差別在於會切換 CPU 到 kernel mode，執行的是 kernel 的程式碼：程式把編號和參數放進暫存器、執行 trap 指令，CPU 跳到 kernel 事先設定的入口，kernel 檢查參數與權限後代為操作硬體，再切回 user mode。這是 application 唯一能碰硬體的合法途徑。</p>',
    a60: '<p>CPU 有 mode bit 區分 user 與 kernel mode；I/O 指令、修改 page table 等特權指令只能在 kernel mode 執行，user 程式執行會 trap。所以程式要讀檔案不能自己對磁碟下指令，必須透過 system call。</p><p>流程：libc 的包裝函式把 system call 編號（如 SYS_read）和參數放進約定暫存器，執行 syscall 指令 → CPU 切到 kernel mode、跳到 system call 入口 → kernel 用編號查表找到 sys_read，驗證 fd 和 buffer 合法 → 執行（可能觸發 I/O 讓 process 進 Waiting）→ 把結果放暫存器，sysret 回 user mode。</p><p>成本比函式呼叫高很多（模式切換、參數驗證、cache 影響），所以 libc 會 buffering——printf 不一定每次都 write。</p>',
    followup: '「printf 是 system call 嗎？」——不是，它是 libc 函式，內部呼叫 write。「怎麼觀察程式發出哪些 system call？」——strace。',
    link: '#/ch/ch0/syscall' },
  { id: 'iv-interrupt', tag: 'OS 基礎', q: 'Interrupt 是什麼？OS 為什麼需要它？',
    hint: '硬體訊號、保存狀態、vector table；兩個用途：裝置通知與 timer。',
    a30: '<p>Interrupt 是硬體發給 CPU 的訊號，讓 CPU 暫停目前工作、保存 PC 與狀態、跳到 kernel 的 handler，處理完再還原。它有兩個關鍵用途：讓慢速裝置在完成時通知 CPU，CPU 不用一直 polling；以及 timer interrupt 讓 kernel 定期取回控制權，是搶佔式排程的基礎——沒有它，一個無窮迴圈就能霸佔 CPU。</p>',
    a60: '<p>CPU 每執行完一條指令會檢查 interrupt 線。有訊號時硬體自動切到 kernel mode、把 PC 和狀態推進 kernel stack，用 interrupt 編號查 interrupt vector table 找到對應的 handler（ISR）並跳過去。Handler 處理裝置（例如把資料搬走、把等待該 I/O 的 process 改成 Ready），結束後還原狀態、切回 user mode——是否回到原本的 process 由 scheduler 決定。</p><p>Trap 或 exception 是同步版本：由目前指令引發，例如 system call、page fault、除以零，處理流程相同。</p><p>現代 OS 是事件驅動的：kernel 平常不主動執行，全靠 interrupt 和 system call 觸發。</p>',
    followup: '「interrupt 處理時能再被 interrupt 嗎？」——看設計，通常有優先權，高優先可以打斷低優先的 handler。',
    link: '#/ch/ch0/interrupt' },
  { id: 'iv-user-kernel', tag: 'OS 基礎', q: '為什麼 application 不能直接控制硬體？',
    hint: '保護；mode bit；特權指令；system call 是守門員。',
    a30: '<p>因為 CPU 硬體不允許：user mode 下執行 I/O 指令、修改 page table、關閉 interrupt 這類特權指令會直接 trap。如果允許，任何有 bug 或惡意的程式都能讀別人的記憶體、鎖死系統、破壞磁碟。所以所有硬體操作都必須經由 system call 交給 kernel，由 kernel 檢查權限、仲裁資源、再代為執行。</p>',
    a60: '<p>OS 的核心職責之一是保護：process 之間互不干擾、使用者程式不能破壞系統。實現的基礎是 dual-mode operation——CPU 有 mode bit，特權指令只在 kernel mode 有效。</p><p>如果 user 程式能直接下 I/O 指令，它可以讀任何檔案、繞過權限；能改 page table 暫存器就能存取任何記憶體；能關 interrupt 或改 timer 就能永遠霸佔 CPU。所以這些全是特權指令。</p><p>Kernel 透過 system call 提供受控的門：程式提出請求，kernel 驗證參數（fd 是你的嗎？buffer 在你的位址空間嗎？）、檢查權限、排程資源、執行、回傳。這樣硬體的複雜性和危險性被封裝在 kernel 裡，程式只看到 read/write 這種簡單、安全的抽象。</p>',
    followup: '「那 kernel 自己的 bug 呢？」——會讓整個系統崩潰，這是 microkernel 想解決的問題（把驅動程式移到 user space）。',
    link: '#/ch/ch0/kernel-modes' },
  { id: 'iv-fork-exec', tag: 'Process & Thread', q: 'fork() 和 exec() 各做什麼？為什麼分成兩個？',
    hint: 'fork 複製、exec 替換；shell 怎麼用它們。',
    a30: '<p>fork() 複製目前 process，產生一個幾乎一模一樣的 child（自己的位址空間副本、PID 不同、fork 回傳值不同）。exec() 把目前 process 的程式碼和資料整個換成另一個程式，PID 不變。分開的好處是 fork 和 exec 之間 child 可以先設定環境——重導向 fd、改變工作目錄——這正是 shell 執行指令的方式。</p>',
    a60: '<p>fork() 在 parent 回傳 child 的 PID、在 child 回傳 0，兩者從 fork 的下一行各自繼續。位址空間用 copy-on-write 共享，直到某方寫入才真的複製那一頁，所以 fork 很快。fd table 也複製，父子共用同一筆 open file entry。</p><p>exec() 家族（execve 等）用新程式的 text、data、stack、heap 取代目前 process 的內容，從新程式的 main 開始；PID、fd 都保留。</p><p>Shell 執行 ls &gt; out.txt 時：fork → child 裡 open out.txt、dup2 到 fd 1 → exec ls。ls 完全不知道自己的輸出被重導向。這種「先複製再替換」的組合讓 process 建立既簡單又有彈性，是 UNIX 設計的經典。</p>',
    followup: '「fork 後 child 先跑還是 parent 先跑？」——不保證，由 scheduler 決定。「zombie process 是什麼？」——child 結束但 parent 還沒 wait()，PCB 仍保留。',
    link: '#/ch/ch1/program-process' },
  { id: 'iv-fragmentation', tag: 'Memory', q: 'Internal 和 External Fragmentation 有什麼不同？',
    hint: '浪費在區塊內 vs 區塊間；固定 vs 可變；paging 的角色。',
    a30: '<p>Internal fragmentation 是分配的區塊比實際需求大，多出來的部分在區塊內部浪費掉，發生在固定大小的分配（固定分割、paging 的最後一頁）。External fragmentation 是空閒空間總量夠，但分散成很多小 hole，沒有一塊連續的夠用，發生在可變大小的連續配置。Paging 消除了 external fragmentation，代價是引入 internal fragmentation。</p>',
    a60: '<p>可變分割下 process 來去會留下大小不一的 hole；first/best/worst fit 都無法根本解決，久了三分之一的記憶體可能被碎片鎖住（50% rule）。這是 external fragmentation，解法是 compaction（需要執行時重定位，成本高）或改用 paging。</p><p>Paging 把記憶體切成固定大小的 frame，任何 frame 都能用，所以沒有「hole 太小」的問題；但 process 大小不是 page 的整數倍，最後一頁平均浪費半頁——這是 internal fragmentation。page size 越小碎片越少但 page table 越大。</p><p>檔案系統的 block、固定分割的 partition 也有同樣的 internal fragmentation；malloc 的 heap 則有 external fragmentation。</p>',
    followup: '「segmentation 有哪種碎片？」——external（segment 大小可變）。',
    link: '#/ch/ch7/fragmentation' },
  { id: 'iv-producer-consumer', tag: 'Synchronization', q: 'Producer-Consumer 問題怎麼用 semaphore 解？為什麼需要三個？',
    hint: 'mutex / empty / full 各管什麼；wait 順序錯會 deadlock。',
    a30: '<p>用三個 semaphore：mutex（初始 1）保護 buffer 的互斥；empty（初始 N）計算空位，producer 放東西前 wait(empty)，滿了就等；full（初始 0）計算物品數，consumer 拿之前 wait(full)，空了就等。Producer 是 wait(empty)、wait(mutex)、放、signal(mutex)、signal(full)；consumer 對稱。順序不能反：先拿 mutex 再等 empty，buffer 滿時會 deadlock。</p>',
    a60: '<p>Bounded buffer 有三個需求：兩個人不能同時改 in/out 指標（互斥）、滿了 producer 要等、空了 consumer 要等。一個 mutex 只能做第一件事，因為它沒有「等某個計數大於零」的能力，所以需要 counting semaphore。</p><p>empty 和 full 的和恆等於 N（扣掉正在操作的）：producer 消耗一個 empty、生產一個 full；consumer 相反。這種「一方 wait、另一方 signal」的用法正是 semaphore 沒有擁有權的意義。</p><p>經典錯誤是把 wait(mutex) 放在 wait(empty) 之前：buffer 滿時 producer 拿著 mutex 睡在 empty 上，consumer 要 mutex 也睡，互相等待。規則：先等資源條件，再拿互斥鎖。</p>',
    followup: '「多個 producer 多個 consumer 也適用嗎？」——適用，mutex 已保護 in/out。',
    link: '#/ch/ch5/producer-consumer' },
  { id: 'iv-fd', tag: 'File System', q: 'open() 回傳的 file descriptor 是什麼？read() 怎麼知道從哪裡讀？',
    hint: '三層表：fd table → open file table（offset）→ inode。',
    a30: '<p>File descriptor 是 process 自己的開啟檔案表的索引，一個小整數。它指向 kernel 全系統的 open file table 項目，裡面記著目前的 offset 和模式，再指向 inode——檔案的 metadata 和資料 block 位置。read() 用 fd 找到那筆項目，從 offset 開始讀，讀完把 offset 往前推，所以連續 read 會讀到後面的內容。</p>',
    a60: '<p>open() 沿路徑查目錄找到 inode 號碼，把 inode 讀進記憶體、檢查權限，在 open file table 建一筆（offset 0、模式、inode 指標、refcount），再在 process 的 fd table 找最小空位放指標，回傳那個索引。0、1、2 預設是 stdin、stdout、stderr。</p><p>read(fd, buf, n)：fd → open file entry → 用 offset 和 inode 的 block 表算出資料在哪個磁碟 block，透過 buffer cache 讀取，複製到 buf，offset 加上實際讀到的 byte 數。</p><p>fork 複製 fd table 但指向同一筆 open file entry，所以父子共享 offset；這是 shell 重導向、pipe 的基礎。close() 清 fd 格子、refcount 減一，歸零才釋放；檔名不在 inode 裡，在目錄裡。</p>',
    followup: '「hard link 和 symbolic link？」——hard link 是同一 inode 的另一個名字；symlink 是內容為路徑的特殊檔案。',
    link: '#/ch/ch9/file-basics' }
];
