/* OS Trace Mode 題庫：情境 → 事件 → 先預測 → 動畫驗證 */
window.TRACES = [
  { id: 'tr-timer', tag: 'Process State', title: 'Timer Interrupt 之後誰的狀態改變？',
    scene: '<div class="queue"><span class="q-item run">P1: Running</span><span class="q-item">P2: Ready</span><span class="q-item wait">P3: Waiting（等 I/O）</span></div><p style="margin:8px 0 0">單核 CPU，Time = 0。排程是 Round Robin。</p>',
    event: 'Timer Interrupt（P1 的時間片用完）',
    q: '接下來哪些 process 的狀態會改變？',
    options: ['只有 P1：Running → Waiting', 'P1：Running → Ready；P2：Ready → Running', 'P1 → Ready；P3 → Running（P3 等最久）', 'P1、P2、P3 都變 Ready'],
    answer: 1,
    explanation: 'Timer interrupt 把 P1 踢回 Ready（它沒有在等任何事件，只是時間到）。Scheduler 從 Ready Queue 挑 P2 上 CPU。P3 還在等 I/O，跟 timer 無關，維持 Waiting——就算 CPU 空著它也不能跑。',
    anim: { sim: 'processState', simOpts: { preset: [{ id: 'P1', state: 'Running' }, { id: 'P2', state: 'Ready' }, { id: 'P3', state: 'Waiting' }], script: [['timer', 'P1'], ['dispatch', 'P2']], note: '動畫已自動套用 timer interrupt 與 dispatch。你可以繼續操作：讓 P3 的 I/O 完成，看它回到哪裡。' } },
    link: '#/ch/ch1/process-state' },
  { id: 'tr-iodone', tag: 'Process State', title: 'I/O 完成後 process 會直接 Running 嗎？',
    scene: '<div class="queue"><span class="q-item run">P2: Running</span><span class="q-item">P1: Ready</span><span class="q-item wait">P3: Waiting（等磁碟）</span></div><p style="margin:8px 0 0">非搶佔式排程（FCFS）。</p>',
    event: '磁碟 Interrupt：P3 要的資料到了',
    q: 'Interrupt handler 處理完之後，三者的狀態是？',
    options: ['P3 Running、P2 Ready、P1 Ready', 'P2 Running、P1 Ready、P3 Ready', 'P2 Running、P1 Ready、P3 Waiting', 'P3 Running、P2 Waiting、P1 Ready'],
    answer: 1,
    explanation: 'I/O 完成 → handler 把 P3 從 Waiting 改成 <b>Ready</b>，排進 Ready Queue（在 P1 後面）。P2 沒有被搶佔（非搶佔式），繼續 Running。P3 要等 P2 讓出 CPU、又輪到它才會 Running。',
    anim: { sim: 'processState', simOpts: { preset: [{ id: 'P2', state: 'Running' }, { id: 'P1', state: 'Ready' }, { id: 'P3', state: 'Waiting' }], script: [['iodone', 'P3']], note: 'P3 回到 Ready。試著對 P3 按 dispatch——按鈕是灰的，因為 P2 還在 CPU 上。' } },
    link: '#/ch/ch1/process-state' },
  { id: 'tr-ctx', tag: 'Context Switch', title: 'Context Switch 時 P1 的暫存器存到哪？',
    scene: '<p>Process A 正在執行，CPU 的 PC = 0x4018、eax = 8。PCB_A 裡的 PC 欄位是上次存的 0x4010。Process B 在 Ready Queue，PCB_B 的 PC = 0x8200。</p>',
    event: 'Timer Interrupt，scheduler 決定換 B',
    q: '切換完成後，PCB_A 的 PC 欄位與 CPU 的 PC 各是多少？',
    options: ['PCB_A.PC = 0x4010，CPU.PC = 0x8200', 'PCB_A.PC = 0x4018，CPU.PC = 0x8200', 'PCB_A.PC = 0x4018，CPU.PC = 0x4018', 'PCB_A.PC = 0x8200，CPU.PC = 0x4018'],
    answer: 1,
    explanation: 'Kernel 先把 CPU 目前的 context（PC = 0x4018、eax = 8）<b>保存</b>進 PCB_A（覆蓋舊的 0x4010），再從 PCB_B <b>載入</b> PC = 0x8200 到 CPU。A 下次被排程時會從 0x4018 繼續。',
    anim: { sim: 'contextSwitch', simOpts: {} },
    link: '#/ch/ch1/context-switch' },
  { id: 'tr-srtf', tag: 'CPU Scheduling', title: 'SRTF：新 process 到達，CPU 會被搶走嗎？',
    scene: '<p>SRTF 排程。t = 0 只有 P1（burst 8）在跑。</p><table class="data mono"><tr><th>Process</th><th>Arrival</th><th>Burst</th></tr><tr><td>P1</td><td>0</td><td>8</td></tr><tr><td>P2</td><td>1</td><td>4</td></tr><tr><td>P3</td><td>2</td><td>2</td></tr></table>',
    event: 't = 1，P2 到達',
    q: 't = 1 到 t = 2 之間 CPU 在跑誰？t = 2 P3 到達後呢？',
    options: ['P1 跑到底（非搶佔）', 'P2（4 < P1 剩餘 7）；t = 2 換 P3（2 < P2 剩餘 3）', 'P2；t = 2 仍是 P2', 'P1；t = 2 換 P3'],
    answer: 1,
    explanation: 'SRTF 每次有人到達就比較剩餘時間。t = 1：P2 的 4 < P1 剩下的 7 → 搶。t = 2：P3 的 2 < P2 剩下的 3 → 再搶。Gantt：P1 | P2 | P3 P3 | P2 P2 P2 | P1 × 7。',
    anim: { sim: 'schedSim', simOpts: { algo: 'SRTF', autoplay: true, title: 'SRTF 自動播放', desc: '看 t = 1、t = 2 的搶佔。' } },
    link: '#/ch/ch3/sjf-srtf' },
  { id: 'tr-rr', tag: 'CPU Scheduling', title: 'RR：時間片用完的同時有新 process 到達',
    scene: '<p>Round Robin，quantum = 2。P1(arrival 0, burst 5) 從 t = 0 開始跑。P2(arrival 2, burst 3)。</p>',
    event: 't = 2：P1 的 quantum 用完，同時 P2 到達',
    q: 't = 2 之後 CPU 先跑誰？Ready Queue 的順序？',
    options: ['P1 繼續（它還沒跑完）', 'P2；queue = [P1]（新到達者先入隊，被換下的排後面）', 'P1；queue = [P2]', '隨機'],
    answer: 1,
    explanation: '慣例（Silberschatz）：同一時刻，新到達的 process 先進 Ready Queue，quantum 用完被換下的排在它後面。所以 t = 2 dispatch P2。Gantt：P1 0–2、P2 2–4、P1 4–6、P2 6–7、P1 7–8。',
    anim: { sim: 'schedSim', simOpts: { algo: 'RR', quantum: 2, procs: [{ id: 'P1', arrival: 0, burst: 5 }, { id: 'P2', arrival: 2, burst: 3 }], autoplay: true } },
    link: '#/ch/ch3/rr' },
  { id: 'tr-race', tag: 'Race Condition', title: '這段交錯最後 counter 是多少？',
    scene: '<p><code>counter = 0</code>。Thread A 與 B 各執行一次 <code>counter++</code>（LOAD / ADD / STORE）。</p>',
    event: '交錯順序：A LOAD → B LOAD → B ADD → B STORE → A ADD → A STORE',
    q: '最後 counter 是？',
    options: ['0', '1', '2', '不確定'],
    answer: 1,
    explanation: 'A LOAD 到 0。B LOAD 到 0、加一、寫回 1。A 用它手上的 0 加一，寫回 1——覆蓋了 B 的結果。少了一次更新。',
    anim: { sim: 'raceCondition', simOpts: { script: 'ABBBAA' } },
    link: '#/ch/ch4/race-condition' },
  { id: 'tr-sem', tag: 'Semaphore', title: 'signal() 之後誰拿到資源？',
    scene: '<p>Counting semaphore S，3 個資源。P1、P2、P3 已各取得一個；P4、P5 依序執行 wait() 後在等待佇列。</p><div class="queue"><span class="q-item">S = −2</span><span class="q-item wait">等待佇列：P4 → P5</span></div>',
    event: 'P2 執行 signal(S)',
    q: 'S 的新值是多少？誰取得資源？',
    options: ['S = −1，P4 取得 P2 釋放的資源', 'S = −1，P5 取得', 'S = 1，沒人取得，資源空著', 'S = 0，P4 與 P5 都取得'],
    answer: 0,
    explanation: 'signal：S 從 −2 變 −1。S ≤ 0 表示還有人在等 → 叫醒佇列第一個 P4，它直接拿到 P2 釋放的那個資源。P5 繼續等。',
    anim: { sim: 'semaphoreSim', simOpts: { script: [['wait', 'P1'], ['wait', 'P2'], ['wait', 'P3'], ['wait', 'P4'], ['wait', 'P5'], ['signal', 'P2']] } },
    link: '#/ch/ch5/semaphore' },
  { id: 'tr-deadlock', tag: 'Deadlock', title: 'B 請求 R1 之後會怎樣？',
    scene: '<div class="queue"><span class="q-item">A 持有 R1</span><span class="q-item">B 持有 R2</span><span class="q-item wait">A 正在等 R2</span></div><p style="margin:8px 0 0">R1、R2 都是單實例資源。</p>',
    event: 'B 請求 R1',
    q: '結果？',
    options: ['B 取得 R1，之後釋放 R2 給 A', 'B 進入等待；A → R2 → B → R1 → A 形成環，deadlock', 'OS 把 R1 從 A 手上收回給 B', 'A 被喚醒'],
    answer: 1,
    explanation: 'R1 在 A 手上，B 等。A 等 B 的 R2，B 等 A 的 R1——單實例資源的 RAG 出現環 = deadlock。四個條件全部成立，沒有外力介入就永遠卡住。',
    anim: { sim: 'deadlockIntro', simOpts: {} },
    link: '#/ch/ch6/deadlock-intro' },
  { id: 'tr-banker', tag: 'Deadlock', title: "Banker's：這個請求該不該核准？",
    scene: '<p>教科書狀態：Available = (3, 3, 2)。P1 的 Allocation = (2, 0, 0)、Need = (1, 2, 2)。</p>',
    event: 'P1 請求 (1, 0, 2)',
    q: 'OS 會？',
    options: ['直接核准，因為 ≤ Available', '拒絕，因為超過 Need', '假裝分配後跑安全性檢查：仍是 safe → 核准', '假裝分配後 unsafe → 拒絕'],
    answer: 2,
    explanation: '(1,0,2) ≤ Need (1,2,2) ✓，≤ Available (3,3,2) ✓。假裝分配：Available = (2,3,0)，P1 Allocation = (3,0,2)、Need = (0,2,0)。安全性檢查找到序列 P1 → P3 → P4 → P0 → P2 → safe → 核准。',
    anim: { sim: 'bankerSim', simOpts: { autocheck: false } },
    after: '在上面的模擬器：先按「安全性檢查」看原始狀態的 safe sequence，再用底下的「測試請求」輸入 P1 要求 1, 0, 2，看假裝分配後的檢查。',
    link: '#/ch/ch6/banker' },
  { id: 'tr-paging', tag: 'Paging', title: '邏輯位址 13 對應哪個實體位址？',
    scene: '<p>Page size = 4 bytes。</p><table class="data mono"><tr><th>Page</th><th>Frame</th></tr><tr><td>0</td><td>5</td></tr><tr><td>1</td><td>2</td></tr><tr><td>2</td><td>8</td></tr><tr><td>3</td><td>1</td></tr></table>',
    event: 'CPU 送出邏輯位址 13',
    q: 'MMU 算出的實體位址是？',
    options: ['13', '5', '33', '17'],
    answer: 1,
    explanation: '13 ÷ 4 = 3 餘 1 → page 3、offset 1。查表 page 3 → frame 1。實體 = 1 × 4 + 1 = 5。',
    anim: { sim: 'pagingSim', simOpts: { logical: 13, pageSize: 4, pageTable: [5, 2, 8, 1] } },
    link: '#/ch/ch7/paging' },
  { id: 'tr-pagefault', tag: 'Page Fault', title: '存取的 Page 不在 RAM，接下來第一件事是？',
    scene: '<p>Process 執行一條指令，存取 page 5。Page table 中 page 5 的 valid bit = 0。RAM 有一個空 frame。</p>',
    event: 'MMU 發現 valid = 0',
    q: '接下來的順序是？',
    options: ['OS 直接殺掉 process（存取無效頁）', 'trap 進 kernel → 檢查位址合法 → 用空 frame 從磁碟載入 page 5（process 進 Waiting）→ 更新 page table → 重新執行該指令', 'MMU 自己從磁碟讀 page 5，不需要 OS', 'TLB miss，查 page table 後繼續'],
    answer: 1,
    explanation: 'valid = 0 是 page fault，硬體無法處理，trap 給 OS。OS 判斷合法（demand paging 的正常情況）後做磁碟 I/O；process 在等待期間是 Waiting。載入完成更新表、valid = 1，process 回 Ready，再度執行時<b>重新執行</b>那條指令。',
    anim: { sim: 'pageFaultSim', simOpts: {} },
    link: '#/ch/ch8/page-fault' },
  { id: 'tr-lru', tag: 'Page Replacement', title: 'LRU：下一個 page fault 踢誰？',
    scene: '<p>3 個 frame，LRU。Reference string 7 0 1 2 0 3 0 已處理完，frames = [2, 0, 3]，最近使用時間：page 2 → t=3、page 0 → t=6、page 3 → t=5。</p>',
    event: '下一個存取：page 4',
    q: 'Victim 是哪一頁？',
    options: ['2（最久沒用）', '0', '3', '不需要換，有空 frame'],
    answer: 0,
    explanation: 'LRU 看「上次使用時間」最早的：page 2 是 t=3，最舊 → 踢掉。FIFO 會看「載入時間」——這裡剛好也是 2；但如果之前有 hit，兩者會不同。',
    anim: { sim: 'pageReplaceSim', simOpts: { refs: '7 0 1 2 0 3 0 4', frames: 3, algo: 'LRU', autoEnd: true } },
    link: '#/ch/ch8/page-replacement' },
  { id: 'tr-syscall', tag: 'System Call', title: 'read() 呼叫過程中，CPU 模式怎麼變？',
    scene: '<p>User 程式執行 <code>read(fd, buf, 100)</code>。目前 CPU 在 user mode。</p>',
    event: 'libc 執行 syscall 指令',
    q: '此後直到 read() 回傳，模式的變化是？',
    options: ['一直是 user mode，因為 read 是 libc 函式', 'user → kernel（trap）→ kernel 執行 sys_read、可能等 I/O → user（sysret）', 'user → kernel，之後一直留在 kernel mode', 'kernel → user'],
    answer: 1,
    explanation: 'syscall 指令把 mode bit 切到 kernel、跳到 system call 入口；kernel 驗證參數、對裝置下指令（process 可能進 Waiting）、複製資料到 buf；sysret 切回 user mode。程式本身無感，但中間經歷了兩次模式切換。',
    anim: { sim: 'syscallSim', simOpts: {} },
    link: '#/ch/ch0/syscall' },
  { id: 'tr-pc-full', tag: 'Semaphore', title: 'Buffer 滿了，Producer 會停在哪一行？',
    scene: '<p>Bounded buffer N = 5，已經放滿 5 個。empty = 0、full = 5、mutex = 1。Consumer 目前沒在跑。</p>',
    event: 'Producer 執行到 wait(empty)',
    q: 'Producer 的狀態？mutex 的值？',
    options: ['Producer 通過，覆寫 buffer[0]', 'Producer 在 wait(empty) 阻塞（empty 變 −1）；mutex 仍是 1，consumer 之後可以正常進入', 'Producer 在 wait(mutex) 阻塞', 'Producer 在 wait(empty) 阻塞，且 mutex = 0，consumer 也進不去'],
    answer: 1,
    explanation: 'empty = 0 → wait 使它變 −1，producer 進等待佇列。因為 wait(empty) 在 wait(mutex) <b>之前</b>，producer 沒有拿著 mutex 睡覺，consumer 可以拿 mutex 取出一個東西、signal(empty) 叫醒 producer。若順序反過來就是 deadlock。',
    anim: { sim: 'producerConsumer', simOpts: {} },
    after: '在模擬器裡：連按 Producer 25 次（放滿 5 個，每個 5 步），再按一次 Producer，看它在 wait(empty) 被擋；接著按 Consumer 逐步操作，看 producer 被叫醒。',
    link: '#/ch/ch5/producer-consumer' }
];
